site_name: NKDACS
site_description: NKDACS 是一个南开大学统计与数据科学学院属下的科研组织，向学界及社会各界提供统计咨询服务。
site_url: 'https://www.nkdacs.com'
strict: true
repo_url: 'https://github.com/NKDACS/NKDACS-Website'
edit_uri: 'edit/master/docs/'
remote_branch: gh-pages
remote_name: 'origin'
site_author: NKDACS IT Team
copyright: 'Copyright &copy; 2017 - 2018 NKDACS'

nav:
  - 主页: index.md
  - 案例比赛:
    - 案例比赛: competition/case.md
  - 统计咨询:
    - 咨询案例: consulting/all.md
  - 知识分享:
    - The Bootstrap: share/bootstrap/bootstrap.md
    - Chapter 1: share/chap1/chap1.md
    - Random number: share/Random number/Random number.md
  - 教程:
    - Markdown 模板: tutorial/md-template.md
    - Markdown 说明: tutorial/md-tutorial.md
    - Pytorch安装教程: tutorial/pytorch-install.md
  - 关于:
    - 网站简介: about/website-intro.md
    - 团队介绍: about/intro.md
    - 组织架构: about/structure.md
  - 其他:
    - 知识共享协议: others/cc.md
    - 更换站点颜色: others/color.md

theme:
  name: 'material'
  font: false
  language: 'zh'
  logo:
    icon: 'school'
  palette:
    primary: 'blue grey'
    accent: 'light blue'
  include_search_page: false
  search_index_only: true
  feature:
    tabs: true

extra:
  search:
    language: 'jp'
  social:
    - type: 'github'
      link: 'https://github.com/NKDACS'
    - type: 'globe'
      link: 'http://stat.nankai.edu.cn/'
extra_javascript:
  - _static/js/extra.js
  - //cdn.bootcss.com/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_SVG

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
